title: Grimgrimberg
description: Software Developer | Problem Solver | Tech Enthusiast
baseurl: ""
url: "https://grimgrimberg.github.io"

# Social links
github_username: grimgrimberg
linkedin_username: yuval-grimberg-933215173  # LinkedIn username
email: your.email@example.com  # Add your email here

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
show_downloads: false 