title: Your Name
description: Software Developer | Problem Solver | Tech Enthusiast
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # your site's URL

# Social links
github_username: your-username
linkedin_username: your-username
email: your.email@example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
show_downloads: false